settings:
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  host: localhost
  port: 4321                       # realize服务的端口, 并非启动服务的端口号
schema:
  - name: novel
    path: .                          # 执行文件的所在路径
    commands:                        # 并非每个command都是必须的, 我一般只用到install和run
      install:
        status: false
      run:
        status: true
    args:                             # 额外参数, 主要是run的时候用到
      - --key1=value1
      - --key2=value2
    watcher:
      paths:                          # 监听文件变化的路径
        - /
      extensions:                     # 监听的文件的文件拓展类型
        - go
      ignored_paths:                  # 无需监听的路径
        - vendor
      scripts:                        # 执行的脚本
        - type: before                  # 实行脚本的时机, 这里是启动前
          command: tskill novel    # 和go.mod里面的package名称一样, 用来杀进程的, 避免端口占用, 重启失败
          output: false
